@startuml
hide empty members
hide circle
left to right direction
skinparam nodesep 50

class "<:martial_arts_uniform:> Judoist" as Judoist {
<#transparent,#transparent>|<:link:>| id| iri| 1..1|
}

class "<:chains:> Nunchaku" as Nunchaku {
<#transparent,#transparent>|<:link:>| id| iri| 1..1|
}

class "<:japan:> Japan" as Japan {
<#transparent,#transparent>|<:link:>| id| iri| 1..1|
}

class "<:basketball:> BasketballPlayer" as BasketballPlayer {
<#transparent,#transparent>|<:link:>| id| iri| 1..1|
}

Judoist                           -d-> "0..*" BasketballPlayer           : beats
Judoist                           -r-> "2..2" Nunchaku                   : uses
Nunchaku                          -r-> "1..1" Japan                      : boughtFrom
@enduml
